---
title: "part 3"
output: html_document
date: "2024-07-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
library(tidyverse)
library(zoo)
library(carat)
library(lmtest)
library(sandwich)
library(car)
```


```{r}
Professor <- read_csv("professor.csv")
Grades_Enrollment <- read_csv("GradesEnrollment.csv")
```


```{r}
Grades_Enrollment_StudentInfo <- Grades_Enrollment %>%
  select(SUID, Class_Code, `Ethnic Group Code Desc All`, `Gender Sh Desc`, `Acad Prog Sh Desc`, Sport.x, Term, `Acad Level Begin Term Desc`, `Units Taken in Semester`, `Units Passed in Semester`, `Total Cumulative`,`Curr Gpa`, `Cum Gpa`, `Units Taken`, `Grade Official`, College)

GradeCheck <- Professor %>%
  inner_join(Grades_Enrollment_StudentInfo, by = c("SUID" = "SUID", "Course" = "Class_Code"))

GradeCheck$Grade_Numerical <- ifelse(GradeCheck$Grade == 'A', 4.0, ifelse(GradeCheck$Grade == 'A-', 3.7, ifelse(GradeCheck$Grade == 'B+', 3.3, ifelse(GradeCheck$Grade == 'B', 3.0, ifelse(GradeCheck$Grade == 'B-', 2.7, ifelse(GradeCheck$Grade == 'C+', 2.3, ifelse(GradeCheck$Grade == 'C', 2.0, ifelse(GradeCheck$Grade == 'C-', 1.7, ifelse(GradeCheck$Grade == 'D+', 1.3, ifelse(GradeCheck$Grade == 'D', 1.0, ifelse(GradeCheck$Grade == 'D-', 0.7, ifelse(GradeCheck$Grade == 'F', 0.0, NA))))))))))))

GradeCheck$Grade_Official_Numerical <- ifelse(GradeCheck$`Grade Official` == 'A', 4.0, ifelse(GradeCheck$`Grade Official` == 'A-', 3.7, ifelse(GradeCheck$`Grade Official` == 'B+', 3.3, ifelse(GradeCheck$`Grade Official` == 'B', 3.0, ifelse(GradeCheck$`Grade Official` == 'B-', 2.7, ifelse(GradeCheck$`Grade Official` == 'C+', 2.3, ifelse(GradeCheck$`Grade Official` == 'C', 2.0, ifelse(GradeCheck$`Grade Official` == 'C-', 1.7, ifelse(GradeCheck$`Grade Official` == 'D+', 1.3, ifelse(GradeCheck$`Grade Official` == 'D', 1.0, ifelse(GradeCheck$`Grade Official` == 'D-', 0.7, ifelse(GradeCheck$Grade == 'F', 0.0, NA))))))))))))

GradeCheck[c("Sport")] <- list(NULL)
GradeCheck <- GradeCheck %>%
  rename("Sport" = "Sport.x")

GradeCheck <- GradeCheck %>%
  mutate(GradeDiff = Grade_Official_Numerical - Grade_Numerical)

```


```{r}
GradeCheck2 <- GradeCheck %>%
  subset(!is.na(Grade_Official_Numerical) & !is.na(Grade_Numerical))

GradeCheck2 <- GradeCheck2 %>%
  group_by(SUID, Course, Term) %>%
  summarize(Grade_Numerical = Grade_Numerical, Grade_Official_Numerical = Grade_Official_Numerical, GradeDiff = GradeDiff, AtRiskDummy = AtRiskDummy) %>%
  mutate(CheckCount = n())

table(GradeCheck2$CheckCount)

NumberofChecks <- GradeCheck2 %>%
  subset(CheckCount > 2)

AtRisk <- GradeCheck2 %>%
  subset(AtRiskDummy == 1)

LowerAchievers <- GradeCheck2 %>%
  subset(!Grade_Official_Numerical >= 3.7 & !Grade_Official_Numerical <= 2.3)
```

```{r}
GradeCheckMod <- lm(GradeDiff ~ Grade_Numerical + AtRiskDummy + CheckCount, data = GradeCheck2)
summary(GradeCheckMod)

car::vif(GradeCheckMod)
bptest(GradeCheckMod)
bptest(GradeCheckMod, ~ Grade_Numerical*AtRiskDummy*CheckCount + I(Grade_Numerical^2) + I(AtRiskDummy^2) + I(CheckCount^2), data = GradeCheck2)

coeftest(GradeCheckMod, vcov=hccm)



CheckCountMod <- lm(GradeDiff ~ Grade_Numerical + AtRiskDummy + CheckCount, data = NumberofChecks)
summary(CheckCountMod)

car::vif(CheckCountMod)
bptest(CheckCountMod)
bptest(CheckCountMod, ~ Grade_Numerical*AtRiskDummy*CheckCount + I(Grade_Numerical^2) + I(AtRiskDummy^2) + I(CheckCount^2), data = NumberofChecks)

coeftest(CheckCountMod, vcov=hccm)


LowAchieversMod <- lm(GradeDiff ~ Grade_Numerical + AtRiskDummy + CheckCount, data = LowerAchievers)
summary(LowAchieversMod)

car::vif(LowAchieversMod)
bptest(LowAchieversMod)
bptest(LowAchieversMod, ~ Grade_Numerical*AtRiskDummy*CheckCount + I(Grade_Numerical^2) + I(AtRiskDummy^2) + I(CheckCount^2), data = LowerAchievers)

coeftest(LowAchieversMod, vcov=hccm)


sum(GradeCheck2$Grade_Official_Numerical >= 3.7)

sum(GradeCheck2$Grade_Official_Numerical <= 2.3)

```





```{r}
Grades_with_comments <- Grades %>%
  left_join(Professor, by = c("SUID" = "SUID", "Sport.x" = "Sport", "Class_Code" = "Course"))

ComboJoinSport <- unique(Grades_with_comments[c("Sport.x","Sport.y")])
ComboJoinSport <- ComboJoinSport %>% mutate(IsConsistent=ifelse(`Sport.x`==`Sport.y`,1,0))

Grades_with_comments[c("Sport.y", "Submitted On", "Grade", "Section.y", "Comments")] <- list(NULL)

Grades_with_comments <- Grades_with_comments[!duplicated(Grades_with_comments), ]

Grades_with_comments <- Grades_with_comments %>%
  rename("Sport" = "Sport.x")

#Grades_with_comments$Comments[is.na(Grades_with_comments$Comments)] <- "No Comment"
#Grades_with_comments$Comments <- ifelse(Grades_with_comments$Comments == "N/A", "No Comment", Grades_with_comments$Comments)

table(Grades_with_comments$Comments)


```

